### ISSUE TITLE
props for the project

### ISSUE THREAD

**Issue by rimusz** [pieterlange/kube-backup#12]
We have created a similar project based on your one, want to tell big thanks for it.
It backups kubernetes state to S3/GCS buckets
https://github.com/StackPointCloud/kube-state-backup

**Comment by pieterlange** [comment]
Glad it proved useful to you too!

**Comment by pieterlange** [comment]
For anyone hitting this ticket, the project relocated to https://github.com/StackPointCloud/kubernetes-cloud-backup
