### ISSUE TITLE
gpg import failing to execute

### ISSUE THREAD

**Issue by felipejfc** [pieterlange/kube-backup#19]
```
Already on 'master'
Your branch is up-to-date with 'origin/master'.
No local changes to save
gpg: key XXXXXXXXB95FC: "backend <backend@xxx.com>" not changed
gpg: key XXXXXXXXB95FC/1XXXXXXXXXXB95FC: error sending to agent: Not a tty
gpg: error building skey array: Not a tty
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg:       secret keys read: 1
```

Then job fail.

This is when using with git crypt enabled :/

**Comment by pieterlange** [comment]
I admit i haven't actually used the GPG extentions yet 😬 

@krogon-dp any ideas?

**Comment by krogon** [comment]
@felipejfc 
1. What image/tag do you use?
1. Does your private key is secured with passphrase?

**Comment by krogon-dp** [comment]
@felipejfc 
1. What image/tag do you use?
1. Does your private key is secured with passphrase?

**Comment by felipejfc** [comment]
@krogon-dp 

1) latest
2) no

**Comment by pieterlange** [comment]
@felipejfc can you give a little more context on how you deployed the application so we can have a fighting chance to reproduce this and help you solve the problem? Thanks.

**Comment by pieterlange** [comment]
@felipejfc ping.

**Comment by felipejfc** [comment]
@pieterlange I just followed exactly as in here https://github.com/pieterlange/kube-backup#enable-git-crypt
