### ISSUE TITLE
send alert when backup job failed

### ISSUE THREAD

**Issue by humiaozuzu** [pieterlange/kube-backup#23]
Can you add an option to send alert message to slack or sentry when cron job failed?

Thank you for you great work.

**Comment by pieterlange** [comment]
Have you tried https://github.com/getsentry/sentry-kubernetes? It should work fine for this.

**Comment by pieterlange** [comment]
I do not think this functionality should be part of this project. Instead, use generic alerting/monitoring tools for your cronjobs.

**Comment by pieterlange** [comment]
https://medium.com/@tristan_96324/prometheus-k8s-cronjob-alerts-94bee7b90511 - cronjob alerts with prometheus
