### ISSUE TITLE
entrypoint.sh fails

### ISSUE THREAD

**Issue by p-bakker** [pieterlange/kube-backup#33]
It fails on clusters that don't have one of the resources types specified (or hardcoded in entrypoint.sh) in the cluster, like for example customresourcedefinition or clusterissuer

**Comment by pieterlange** [comment]
Thanks for the headsup, i removed the non-standard resourcetypes from the defaults in 6ca4a80. Released as `1.12.0-1`

Your cluster should have `customresourcedefinition` though, unless you're running an ancient version of kubernetes! :)

**Comment by p-bakker** [comment]
Mmm, I'm running on gcp with a cluster created just last week on version 1.10.7-gke.6 of Kubernetes and trying to use your backup logic failed on customresourcedefinition. But a `kubectl get customresourcedefinition` does return something... need to dig in a bit I guess to see whats going on

**Comment by pieterlange** [comment]
Can't help without logs of the failure.

Please paste the output of `kubectl logs -n kube-system kube-state-backup-pod` and `kubectl describe pod -n kube-system kube-state-backup-pod`

**Comment by p-bakker** [comment]
I know, will dig in a bit myself first to see if I can pinpoint why it failed for me on `customresourcedefinition`

**Comment by pieterlange** [comment]
Try removing it from the `RESOURCETYPES` list :)

Ref https://github.com/pieterlange/kube-backup/issues/34
