### ISSUE TITLE
Why convert it to yaml?

### ISSUE THREAD

**Issue by woopstar** [pieterlange/kube-backup#41]
I am wondering why you actually change the output from JSON to Yaml? If you don't you could remove the need for Python, I guess?

```
kubectl get -o=json "$resource" | jq --sort-keys \
        'del(
          .items[].metadata.annotations."kubectl.kubernetes.io/last-applied-configuration",
          .items[].metadata.annotations."control-plane.alpha.kubernetes.io/leader",
          .items[].metadata.uid,
          .items[].metadata.selfLink,
          .items[].metadata.resourceVersion,
          .items[].metadata.creationTimestamp,
          .items[].metadata.generation
      )' | python -c 'import sys, yaml, json; yaml.safe_dump(json.load(sys.stdin), sys.stdout, default_flow_style=False)' >"$GIT_REPO_PATH/$GIT_PREFIX_PATH/${resource}.yaml"
```

Could simply be:

```
kubectl get -o=json "$resource" | jq --sort-keys \
        'del(
          .items[].metadata.annotations."kubectl.kubernetes.io/last-applied-configuration",
          .items[].metadata.annotations."control-plane.alpha.kubernetes.io/leader",
          .items[].metadata.uid,
          .items[].metadata.selfLink,
          .items[].metadata.resourceVersion,
          .items[].metadata.creationTimestamp,
          .items[].metadata.generation
      )' > "$GIT_REPO_PATH/$GIT_PREFIX_PATH/${resource}.json"
```

**Comment by pieterlange** [comment]
YAML makes for cleaner diffs (no curly braces etc) which makes it easier to spot what changed between iterations.

Forking out to python for the YAML conversion does feel a bit dirty, but i often also use this project as an educational tool for more old-timey sysadmins (that lean on bash :) )
The python dependency only increases the image size by a little considering we're also dropping in a kubectl binary.

**Comment by woopstar** [comment]
Point taken for fewer diffs due to the curly braces etc. I did not think of that. I was just wondering as you already did dump the data as JSON, and as this tool makes a "backup" - why would you then convert it back to Yaml again.

**Comment by woopstar** [comment]
FYI. If you have an HPA attached to a deployment, it will give diff's when it scales as it changes the replica count in the deployment.

**Comment by pieterlange** [comment]
Yeah i know.. we could add it to the filtered spec list but i figured most people *do* want to know how many pods they have running.
