### ISSUE TITLE
Can't download alpine image + questions

### ISSUE THREAD

**Issue by RunlevelConsulting** [pieterlange/kube-backup#42]
I'm still fairly new to this kind of thing but running the Dockerfile seems to fail with the following:

```
# docker build -t backup .
Sending build context to Docker daemon  139.3kB
Step 1/13 : FROM alpine:3.7
3.7: Pulling from library/alpine
c67f3896b22c: Pull complete 
Digest: sha256:a52b4edb6240d1534d54ee488d7cf15b3778a5cfd0e4161d426c550487cddc5d
Status: Downloaded newer image for alpine:3.7
 ---> 34ea7509dcad
Step 2/13 : RUN apk update &&   apk add --update     bash     easy-rsa     git     openssh-client     curl     ca-certificates     jq     python     py-yaml     py2-pip     libstdc++     gpgme     libressl-dev     make     g++     &&   git clone https://github.com/AGWA/git-crypt.git &&   make --directory git-crypt &&   make --directory git-crypt install &&   rm -rf git-crypt &&   apk del libressl-dev make g++ &&   rm -rf /var/cache/apk/*
 ---> Running in 958dbf103f72
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.70c88391.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.5022a8a2.tar.gz: No such file or directory
2 errors; 13 distinct packages available
The command '/bin/sh -c apk update &&   apk add --update     bash     easy-rsa     git     openssh-client     curl     ca-certificates     jq     python     py-yaml     py2-pip     libstdc++     gpgme     libressl-dev     make     g++     &&   git clone https://github.com/AGWA/git-crypt.git &&   make --directory git-crypt &&   make --directory git-crypt install &&   rm -rf git-crypt &&   apk del libressl-dev make g++ &&   rm -rf /var/cache/apk/*' returned a non-zero code: 2
```
I tested to see if it was a network issue specific to my server by changing FROM to 'ubuntu' and that downloaded just fine. The URL is available and I'm able to download the file normally. Am I doing something wrong?

--

I'm trying to hook my K8 cluster to my BitBucket account but am finding the README a little difficult to decipher.
1. Where are the environment parameters set? Should they be added into the Dockerfile?

2. Could you also clarify about mounting /backup/.ssh, I need to create that directory on the host and include a VOLUME /backup/.ssh in the Dockerfile?

Any help and clarification would be much appreciated.

**Comment by pieterlange** [comment]
Looks like you just hit some error with the alpinelinux' CDN being unavailable for a bit. It works now..

---
> I'm trying to hook my K8 cluster to my BitBucket account but am finding the README a little difficult to decipher

That sounds like you're not following the readme and deploying this out-of-cluster? You set the environment variables in the runtime configuration ([example for bitbucket](https://github.com/pieterlange/kube-backup/blob/master/cronjob-ssh.yaml)). This is also where the mounts are configured for you. If you follow the steps in the readme to the letter and only adjust your `GIT_REPO` var you should be good to go.
