### ISSUE TITLE
helm chart

### ISSUE THREAD

**Issue by 030** [pieterlange/kube-backup#46]
I think that it would be great if there is a helm chart as one could choose between ssh and aws-git and that could be defined in the values.yml.

Shall I create a helm chart and should this be created in [this repository](https://github.com/helm/charts) or is it fine to add it to this project?

**Comment by pieterlange** [comment]
I didn't create a helm chart for this project because there's considerable other manual tasks to be executed (generate SSH keys, set up external repo) and the helm chart would add more complexity.

If there's going to be a helm chart it would make sense for it to live in the charts' incubator repo
