### ISSUE TITLE
images disappeared of docker hub?

### ISSUE THREAD

**Issue by davidkarlsen** [pieterlange/kube-backup#68]
https://hub.docker.com/r/ptlange/kube-backup/tags
there used to be a 1.12.0 tag - but the newer tags seems to be gone.
zup?

**Comment by pieterlange** [comment]
Weird. Must be some bug with the github<>dockerhub build integration. It always seemed janky. I'll reupload soon.

But highly recommend to host your own images since you're giving my own janky bash code an awful lot of permissions in your clusters :P
